# Generated by Django 3.2.5 on 2022-08-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=64)),
                ('definition', models.CharField(max_length=2048)),
                ('descriptions', models.CharField(max_length=2048)),
                ('parentDir', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
