# Generated by Django 3.2.5 on 2022-08-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columns',
            old_name='descriptions',
            new_name='description',
        ),
    ]
