# Generated by Django 3.2.5 on 2022-08-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220805_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='columns',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='columns',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
